### ISSUE TITLE
Error 'this._onLogFn is not a function' is thrown with library data loading 

### ISSUE THREAD

**Issue by Zhirong2022** [sassoftware/vscode-sas-extension#369]
**Describe the bug**
Install the SAS extension base on the latest Main branch. Sign in and try to load SAS contents, it failed to load data under Libraries with error 'this._onLogFn is not a function'.

**Steps to reproduce**

1.Sign in with a valid profile

**Expected behavior**
It can load Libraries data successfully without error

**Screenshots**
![image](https://github.com/sassoftware/vscode-sas-extension/assets/121005702/34a3a097-29d3-458a-90b7-382bf358b9b4)

**Environment (please complete the following information):**
Client OS: [e.g. Windows 11]
Extension version: [e.g. v1.0.0]

**Comment by scnwwu** [comment]
Regression introduced by #355
Library view requires a session. But it does not need to view any log. We can check if no _LogFn set, don't retrieve session log.
But if user then run code, as the session already exists, no session log will be shown.
Defer to @smorrisj
